### ISSUE TITLE
XML schema validation failure when signing

### ISSUE THREAD

**Issue by geoffroya** [IdentityPython/pyFF#198]
## Code Version
Pyff 1.1.2

## Behavior
When using pyff to generate/finalize/sign a metadata file - in 2 steps, I get an XML schema validation failure.
I don't have this behaviour when doing everything in one step.

I expect Pyff to deal nicely with the metadata file generated in the first step (generated by pyff)

## Steps to Reproduce
Chaining the 2 following pipelines lead to the issue:
`01-edugain-all-idps.yml`:
```yml
---
- when edugain:
    - filter: "!//md:EntityDescriptor[not(md:Extensions/mdrpi:RegistrationInfo/@registrationAuthority='https://federation.renater.fr/')]"
- when batch:
    - load:
        # RENATER
        - ./main-all-renater-metadata.xml
        # EDUGAIN
        - ./feed-sha256.xml via edugain
        # CRU
        - https://cru.renater.fr/idp/shibboleth
    - select: "!//md:EntityDescriptor[md:IDPSSODescriptor]"
    - sort
    - xslt:
        stylesheet: pp.xsl
    - publish: /tmp/idps-edugain+renater+sac-metadata.xml
    - stats
```
`02-sign-all-idps.yml`:
```yml
---
- load: /tmp/idps-edugain+renater+sac-metadata.xml
- select:
- finalize:
    cacheDuration: PT1H
    validUntil: P9D
- xslt:
    stylesheet: pp.xsl
- sign:
    key: ./sign.key
    cert: ./sign.crt
- publish: /tmp/signed-idps-edugain+renater+sac-metadata.xml
- stats
```

```
$ pyff 01-edugain-all-idps.yml
---
total size:     7867
selected:       3766
          idps: 3766
           sps: 4
---
$ pyff 02-sign-all-idps.yml
ERROR:pyff.builtins:<string>:0:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element '{urn:oasis:names:tc:SAML:2.0:metadata}EntitiesDescriptor': Missing child element(s). Expected is one of ( {urn:oasis:names:tc:SAML:2.0:metadata}Extensions, {urn:oasis:names:tc:SAML:2.0:metadata}EntityDescriptor, {urn:oasis:names:tc:SAML:2.0:metadata}EntitiesDescriptor ).
ERROR:pyff.pipes:XML schema validation failed
Traceback (most recent call last):
  File ".../python3.7/site-packages/pyff/builtins.py", line 469, in publish
    validate_document(req.t)
  File ".../python3.7/site-packages/pyff/utils.py", line 281, in validate_document
    schema().assertValid(t)
  File "src/lxml/etree.pyx", line 3621, in lxml.etree._Validator.assertValid
lxml.etree.DocumentInvalid: Element '{urn:oasis:names:tc:SAML:2.0:metadata}EntitiesDescriptor': Missing child element(s). Expected is one of ( {urn:oasis:names:tc:SAML:2.0:metadata}Extensions, {urn:oasis:names:tc:SAML:2.0:metadata}EntityDescriptor, {urn:oasis:names:tc:SAML:2.0:metadata}EntitiesDescriptor ).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../bin/pyff", line 8, in <module>
    sys.exit(main())
  File ".../python3.7/site-packages/pyff/md.py", line 37, in main
    plumbing(p).process(md, state={'batch': True, 'stats': {}})
  File ".../python3.7/site-packages/pyff/pipes.py", line 308, in process
    scheduler=scheduler).process(self)
  File ".../python3.7/site-packages/pyff/pipes.py", line 253, in process
    return pl.iprocess(self)
  File ".../python3.7/site-packages/pyff/pipes.py", line 281, in iprocess
    raise ex
  File ".../python3.7/site-packages/pyff/pipes.py", line 271, in iprocess
    ot = pipefn(req, *opts)
  File ".../python3.7/site-packages/pyff/builtins.py", line 472, in publish
    raise PipeException("XML schema validation failed")
pyff.pipes.PipeException: XML schema validation failed
```

As running this one - which does all in one pipeline doesn't fail:
`03.yml`:
```yml
---
- when edugain:
    - filter: "!//md:EntityDescriptor[not(md:Extensions/mdrpi:RegistrationInfo/@registrationAuthority='https://federation.renater.fr/')]"
- when batch:
    - load:
        # RENATER
        - ./main-all-renater-metadata.xml
        # EDUGAIN
        - ./feed-sha256.xml via edugain
        # CRU
        - https://cru.renater.fr/idp/shibboleth
    - select: "!//md:EntityDescriptor[md:IDPSSODescriptor]"
    - sort
    - finalize:
        cacheDuration: PT1H
        validUntil: P9D
    - xslt:
        stylesheet: pp.xsl
    - sign:
       key: ./sign.key
       cert: ./sign.crt
    - publish: /tmp/signed-idps-edugain+renater+sac-metadata.xml
    - stats
```
```
$ pyff 03.yml
---
total size:     7867
selected:       3766
          idps: 3766
           sps: 4
---
```

I can't figure out what the problem is. I think that the issue raises during the validation of the generated metadata of `02-sign-all-idps.yml` but didn't manage to make it work.
Does anyone have a idea?

Regards
Geoff.

_Note: feed-sha256.xml comes from http://mds.edugain.org/feed-sha256.xml and main-all-renater-metadata.xml from https://metadata.federation.renater.fr/renater/main/main-all-renater-metadata.xml_

**Comment by geoffroya** [comment]
I figured out what causes the issue: it seems that the `select` in `02-sign-all-idps.yml` doesn't select anything, whereas using `select:  "!//md:EntityDescriptor[md:IDPSSODescriptor]"` makes the trick.

The problem here is that I use the pipeline `02-sign-all-idps.yml` to sign other metadata files, containing SPs or IDPs  or both

**Comment by geoffroya** [comment]
The fact that `select` doesn't select anything in this case is a mistery.

In the mean time, the following workaround should do the trick:

```yaml
---
- load: /tmp/idps-edugain+renater+sac-metadata.xml
- select:
  - "!//md:EntityDescriptor[md:IDPSSODescriptor]"
  - "!//md:EntityDescriptor[md:SPSSODescriptor]"
- finalize:
    cacheDuration: PT1H
    validUntil: P9D
- xslt:
    stylesheet: pp.xsl
- sign:
    key: ./sign.key
    cert: ./sign.crt
- publish: /tmp/signed-idps-edugain+renater+sac-metadata.xml
- stats
```

**Comment by leifj** [comment]
Glad you're making progress! Why don't you try the first buggy example removing the colon after the select, i.e

```yaml
- load: ...
- select
```

**Comment by geoffroya** [comment]
I tries indeed, but it didn't make a difference

**Comment by leifj** [comment]
I know its been a long time but there have been several fixes to pyFF since this was logged - can you test again using the master branch and tell me if it still occurs.

**Comment by leifj** [comment]
ping @geoffroya can you test again with the main branch or at least with 2.0.0
