### ISSUE TITLE
Unexpected handling of xi:include element

### ISSUE THREAD

**Issue by majagw** [IdentityPython/pyFF#203]
pyff `1.1.4` fails while processing a  feed containing `xi:include` element within  IDPSSODescriptor/Extensions 
(see, https://mds.edugain.org/grnet.xml, `EntityDescriptor entityID="https://aai.heal-link.gr/proxy/saml2/idp/metadata.php"`)
The example pipe is:
```
- load:
    - http://mds.edugain.org/grnet.xml 
- select:
- stats
```

pyff gives:
```
ERROR:pyff.samlmd:Error parsing http://mds.edugain.org/grnet.xml: Attempt to load network entity http://mds.edugain.org/scopes/idp.teikal.gr
---
total size:     0
selected:       0
          idps: 0
           sps: 0
```

so all entities are dropped even though a problem exists in one entity.

When publish is added to the pipe there is additional error:
```
ERROR:pyff.samlmd:Error parsing http://mds.edugain.org/grnet.xml: Attempt to load network entity http://mds.edugain.org/scopes/idp.teikal.gr
ERROR:pyff.builtins:<string>:0:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element '{urn:oasis:names:tc:SAML:2.0:metadata}EntitiesDescriptor': Missing child element(s). Expected is one of ( {http://www.w3.org/2000/09/xmldsig#}Signature, {urn:oasis:names:tc:SAML:2.0:metadata}Extensions, {urn:oasis:names:tc:SAML:2.0:metadata}EntityDescriptor, {urn:oasis:names:tc:SAML:2.0:metadata}EntitiesDescriptor ).
ERROR:pyff.pipes:XML schema validation failed
Traceback (most recent call last):
  File "/opt/pyff-1.1.4/lib64/python3.6/site-packages/pyff/builtins.py", line 469, in publish
    validate_document(req.t)
  File "/opt/pyff-1.1.4/lib64/python3.6/site-packages/pyff/utils.py", line 281, in validate_document
    schema().assertValid(t)
  File "src/lxml/etree.pyx", line 3623, in lxml.etree._Validator.assertValid
lxml.etree.DocumentInvalid: Element '{urn:oasis:names:tc:SAML:2.0:metadata}EntitiesDescriptor': Missing child element(s). Expected is one of ( {http://www.w3.org/2000/09/xmldsig#}Signature, {urn:oasis:names:tc:SAML:2.0:metadata}Extensions, {urn:oasis:names:tc:SAML:2.0:metadata}EntityDescriptor, {urn:oasis:names:tc:SAML:2.0:metadata}EntitiesDescriptor ).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pyff-1.1.4/bin/pyff", line 11, in <module>
    load_entry_point('pyFF==1.1.4', 'console_scripts', 'pyff')()
  File "/opt/pyff-1.1.4/lib64/python3.6/site-packages/pyff/md.py", line 37, in main
```

xmllint, xmlwf, Shibboleth MDA handle a feed containing  `xi:include` lines without a problem

**Comment by leifj** [comment]
I realize this issue may be resolved already but this is in fact a feature - SAML metadata is parsed with xinclude turned on. This may not be what you want to do always so I'll provide a config option.
