### ISSUE TITLE
Python 3.10 - ImportError: cannot import name 'MutableMapping' from 'collections'

### ISSUE THREAD

**Issue by malavolti** [IdentityPython/pyFF#240]
## Code Version
2.0.0

## Expected Behavior
No errors on the example provided here: https://pyff.readthedocs.io/en/latest/usage/quickstart.html

## Current Behavior

```bash
(python-pyff) me@desktop[~]: pyff edugain.fd
cherrypy logging disabled
Traceback (most recent call last):
  File "$HOME/python-pyff/bin/pyff", line 5, in <module>
    from pyff.md import main
  File "$HOME/python-pyff/lib/python3.10/site-packages/pyff/md.py", line 14, in <module>
    from .repo import MDRepository
  File "$HOME/python-pyff/lib/python3.10/site-packages/pyff/repo.py", line 3, in <module>
    from .store import make_store_instance, make_icon_store_instance
  File "$HOME/python-pyff/lib/python3.10/site-packages/pyff/store.py", line 17, in <module>
    from pyff.resource import IconHandler
  File "$HOME/python-pyff/lib/python3.10/site-packages/pyff/resource.py", line 13, in <module>
    from .parse import parse_resource
  File "$HOME/python-pyff/lib/python3.10/site-packages/pyff/parse.py", line 2, in <module>
    from .utils import parse_xml, root, first_text, unicode_stream, find_matching_files
  File "$HOME/python-pyff/lib/python3.10/site-packages/pyff/utils.py", line 25, in <module>
    import xmlsec
  File "$HOME/python-pyff/lib/python3.10/site-packages/xmlsec/__init__.py", line 17, in <module>
    import xmlsec.crypto
  File "$HOME/python-pyff/lib/python3.10/site-packages/xmlsec/crypto.py", line 24, in <module>
    from collections import MutableMapping as DictMixin
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

## Possible Solution
Python Documentation says:

_Deprecated since version 3.3, will be removed in version 3.10: Moved [Collections Abstract Base Classes](https://docs.python.org/3.9/library/collections.abc.html#collections-abstract-base-classes) to the [collections.abc](https://docs.python.org/3.9/library/collections.abc.html#module-collections.abc) module. For backwards compatibility, they continue to be visible in this module through Python 3.9._ 

(https://docs.python.org/3.9/library/collections.html#module-collections)

so into the following file:

* `lib/python3.10/site-packages/xmlsec/crypto.py`

`collections` must be replaced with `collections.abc`.

## Steps to Reproduce

1. `cd $HOME`
2. `sudo apt install python3 python3-pip build-essential python3-dev libxml2-dev libxslt1-dev libyaml-dev python3-virtualenv`
3. `virtualenv python-pyff`
4. `python3 --version` (check Python Version. On Ubuntu 22.04.1 LTS I have Python v3.10.6)
5. `source python-pyff/bin/activate`
6. `pip install --upgrade pip`
7. `pip install -U pyff`
8. `source ~/.profile`
9. `vim edugain.fd`

    ```bash
    - load:
       - http://mds.edugain.org
    - select:
    - stats:
    ```
10. `pyff edugain.fd`

## Question

How to solve this problem without change manually the crypto.py library?

Thank you so much!

Marco

**Comment by c00kiemon5ter** [comment]
This is fixed by the latest release of pyXMLsecurity.
The fix is included on version `0.30`.
